Datadog addon docs
aws-quickstart/cdk-eks-blueprints pull request #356
Opened 2022-04-13 18:22 UTC by khewonc

*Issue #, if available:*

*Description of changes:*

Document the DatadogAddOn.

2022-04-14 03:00 UTC, shapirov103 requested changes
Thank you for your contribution! Looks great overall, one small comment.

2022-04-14 21:12 UTC, khewonc commented on docs/addons/datadog.md
> +## Usage
Thanks for the review! I added an install section and a teammate submitted a PR for a pattern: https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/25

2022-04-15 02:46 UTC, shapirov103 reviewed
@khewonc do you mind also adding a reference to the datadog page in the mkdocs.yml (in the root) under `AddOns`? It will make it appear under the nav panel in the documentation portal and improve discoverability.

2022-04-18 00:41 UTC, shapirov103 approved these changes
LGTM

2022-04-18 00:49 UTC, merged