Bump ArgoCD default version to latest
aws-quickstart/cdk-eks-blueprints pull request #751
Opened 2023-07-05 16:23 UTC by tsahiduek

Argo CD helm version is outdated.
Helm chart version 5 introduced couple of changes, and I think we should upgrade it. It was tested on the pipeline-multi-env-gitops pattern

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-05 16:26 UTC, elamaran11 approved these changes
LGTM

2023-07-05 17:14 UTC, shapirov103 commented
@tsahiduek the reason why I deferred upgrade to the latest version was because of the differences they introduced in handling private repositories. That is SSH key, github token, user/pwd authorization. Before we merge it, have you validated the current approach still works? I believe my initial research spotted some incompatibilities.

2023-07-05 17:15 UTC, shapirov103 requested changes
Please see my comment on private repo support. Happy to merge if it is not going to break the patterns for private repos.

2023-07-05 21:23 UTC, tsahiduek commented
> 

Hi @shapirov103 ,
I've tested this with the GitOps Multi-env pattern that uses ArgoCD with SSH connection type --> https://github.com/aws-samples/cdk-eks-blueprints-patterns/blob/main/lib/pipeline-multi-env-gitops/index.ts#L250
Is this is what you meant?

2023-07-06 16:11 UTC, shapirov103 reviewed
@tsahiduek I also see indirect confirmation of the quality/compatibility here: https://github.com/aws-quickstart/cdk-eks-blueprints/issues/671#issuecomment-1623680147

LGTM

2023-07-06 16:11 UTC, shapirov103 approved these changes
LGTM

2023-07-06 16:12 UTC, shapirov103 commented
/do-e2e-tests

2023-07-06 17:26 UTC, merged