Observability Builder Props for Addons
aws-quickstart/cdk-eks-blueprints pull request #833
Opened 2023-08-29 22:35 UTC by Howlla

*Issue #, if available:*~

*Description of changes:* Modify some addons to export their Type for props.
Modify observability-builder.ts to accept props for each addon

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-30 14:01 UTC, elamaran11 requested changes
@Howlla Couple of questions for clarity

2023-08-30 18:42 UTC, Howlla commented on lib/addons/adot/index.ts
> +export type AdotCollectorAddOnProps = Omit<CoreAddOnProps, "saName" | "addOnName" >;
Need to export the props to use in observability builder

2023-08-30 18:44 UTC, Howlla commented on lib/addons/kube-proxy/index.ts
> +    constructor(version?: string, props?: kubeProxyAddOnProps) {
version could be taken in directly from kubeproxyaddon instead.
But previous versions of cdk blueprint took version as first argument so didnt want to modify that.

2023-08-30 18:47 UTC, Howlla commented
To support Fargate cluster deployment we need to be able to pass props for coredns and cert-manager.
Those are the 2 addons that need props in the argument. The rest props were exposed for future use cases that may require configuration values to be passed. 

We can remove the `export type` from coredns and adot but then customers would have to define type again locally in their code

2023-08-30 19:51 UTC, elamaran11 reviewed
LGTM. @shapirov103 Please check and run `e2e`

2023-09-12 00:05 UTC, elamaran11 reviewed
LGTM

2023-09-12 00:31 UTC, shapirov103 reviewed
@Howlla definitely a needed change!

The approach is a bit overloaded from the software engineering perspective and does not align well with the builder pattern which is supposed to abstract the complexity to build the object. 

How about this style to enable prop overrides:

```typescript
     ObservabilityBuilder.builder()
            .account(account)
            .region(region)
            .withAddOnProps(ObservabilityBuilder.ADDON.CoreDns, myCoreDnsProps)
            .withAddOnProps(ObservabilityBuilder.ADDON.CertManager, myCertManagerProps)
            .enableNativePatternAddOns()
            .addOns(...addOns)
            .build(scope, stackId);
```

Please let me know if you have any questions.

2023-09-13 17:36 UTC, Howlla commented
hi @shapirov103 
Could you help me figure out how to properly type this function?

i tried the following way
```
 public withAddOnProps(addon:typeof addons.HelmAddOn|addons.CoreAddOn, props: addons.CoreAddOnProps | addons.HelmAddOnProps ){
        return this.addOns(
            new addon(props)
        )
    }
   ```
   
   but i get the following error
   ```
   This expression is not constructable.
  Not all constituents of type 'CoreAddOn | typeof HelmAddOn' are constructable.
    Type 'CoreAddOn' has no construct signatures.
    ```

2023-09-13 18:09 UTC, shapirov103 commented
> hi @shapirov103 Could you help me figure out how to properly type this function?
> 
> i tried the following way
> 
> ```
>  public withAddOnProps(addon:addons.HelmAddOn | addons.CoreAddOn, props: addons.CoreAddOnProps | addons.HelmAddOnProps ){
>         return this.addOns(
>             new addon(props)
>         )
>     }
> ```
> 
> but i get the following error
> 
> ```
> This expression is not constructable.
> Not all constituents of type 'CoreAddOn | HelmAddOn' are constructable.
>  Type 'CoreAddOn' has no construct signatures.
>  ```
> ```

@Howlla I think the easiest approach is going to be something like:

```typescript
class ObservabilityBuilder {
   
   private certManagerProps: CertManagerAddOnProps;
   private awsLoadbalancerProps: AwsLoadBalancerAddOnProps;
 ...

  public withCertManagerProps(props: CertManagerAddOnProps) {
     this.certManagerProps = props; // actually deep clone here to avoid side effects
  }

  private withAwsLoadBalancerProps(props: AwsLoadBalancerAddOnProps) {
    ...
  }
  
 
}


ObservabilityBuilder.builder()
    .withCertManagerProps( {someprops} )
    .withAwsLoadBalancerProps({some props})
    .enable...()

```

The downside is that for each addon there is an override method, but it makes it easy for the users to consume.

2023-09-15 03:55 UTC, Howlla commented
> > hi @shapirov103 Could you help me figure out how to properly type this function?
> > i tried the following way
> > ```
> >  public withAddOnProps(addon:addons.HelmAddOn | addons.CoreAddOn, props: addons.CoreAddOnProps | addons.HelmAddOnProps ){
> >         return this.addOns(
> >             new addon(props)
> >         )
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but i get the following error
> > ```
> > This expression is not constructable.
> > Not all constituents of type 'CoreAddOn | HelmAddOn' are constructable.
> >  Type 'CoreAddOn' has no construct signatures.
> > ```
> 
> @Howlla I think the easiest approach is going to be something like:
> 
> ```ts
> class ObservabilityBuilder {
>    
>    private certManagerProps: CertManagerAddOnProps;
>    private awsLoadbalancerProps: AwsLoadBalancerAddOnProps;
>  ...
> 
>   public withCertManagerProps(props: CertManagerAddOnProps) {
>      this.certManagerProps = props; // actually deep clone here to avoid side effects
>   }
> 
>   private withAwsLoadBalancerProps(props: AwsLoadBalancerAddOnProps) {
>     ...
>   }
>   
>  
> }
> 
> 
> ObservabilityBuilder.builder()
>     .withCertManagerProps( {someprops} )
>     .withAwsLoadBalancerProps({some props})
>     .enable...()
> ```
> 
> The downside is that for each addon there is an override method, but it makes it easy for the users to consume.

I have made the changes as per your recommendation Mikhail. Will require slight modification to the cdk-eks-observability-accelerator for [these](https://github.com/search?q=repo%3Aaws-observability%2Fcdk-aws-observability-accelerator%20enableOpenSourcePatternAddOns&type=code) files.

2023-09-18 15:35 UTC, shapirov103 commented
@elamaran11 I put my approval on this, looks like it is pending requested changes from your side, please take a look.

2023-09-18 15:58 UTC, merged