Added support for Windows2019 and Windows2022 as amifamily
aws-quickstart/cdk-eks-blueprints pull request #836
Opened 2023-09-05 13:43 UTC by ROunofF

*Issue #, if available:* 

*Description of changes:* Added new values for Windows support of Karpenter : Windows 2019 and Windows2022 with relevant tests.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-05 14:01 UTC, elamaran11 reviewed
LGTM. @youngjeong46 @shapirov103 Please check this

2023-09-08 20:29 UTC, shapirov103 approved these changes
LGTM

2023-09-08 20:31 UTC, merged

2023-09-08 20:34 UTC, shapirov103 requested changes
@ROunofF please run make lint on this - small things in the test file like app is assigned value but not used. Please see my comment on the test file as well.

2023-09-08 20:34 UTC, shapirov103 commented on test/karpenter.test.ts
> +    test("Support Windows2019 as amiFamily", () => {
please make sure github warnings are addressed here, I suppose running `make lint` should be enough to get the errors.

2023-09-08 20:34 UTC, shapirov103 commented on test/karpenter.test.ts
> +            .addOns(new blueprints.KarpenterAddOn({
What is this test case accomplishing, if we never build the blueprint? Do you want to add some expectations here, or at least invoke `build` on the blueprint?

Applies elsewhere.