Konveyor Addon
aws-quickstart/cdk-eks-blueprints pull request #840
Opened 2023-09-14 07:57 UTC by ariveroi

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-14 14:15 UTC, elamaran11 requested changes
@ariveroi Similar comments to Patterns repo but also have more :
1. Since this looks like partner product, Please have partner commenting on the repo for ongoing maintenance.
2. Please share license keys for validation.
3. Documentation needs to be updated per comments for completeness.
4. The addon is not added to addon list documentation [here](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/main/docs/addons/index.md).
5. Please review our partner [extensions](https://aws-quickstart.github.io/cdk-eks-blueprints/extensibility/#partner-extensions) guide once.

2023-09-14 14:15 UTC, elamaran11 commented on docs/addons/konveyor.md
> +Streamline the modernization of your application portfolio to Kubernetes. The Konveyor tool gives you insight throughout the migration process - whether you're making decisions at the portfolio or ap
Same feedback as patterns repo. Start with What is Konveyor and what is its value proposition to customers? Check our other partner addons for example

2023-09-14 14:15 UTC, elamaran11 commented on docs/addons/konveyor.md
> +
Architecture diagram on integration with EKS helps customers to relate it better.

2023-09-14 14:15 UTC, elamaran11 commented on docs/addons/konveyor.md
> +```
Where is the secrets manager command if there is a secret.

2023-09-14 14:15 UTC, elamaran11 commented on docs/addons/konveyor.md
> +
jsdoc for classes helps

2023-09-14 14:15 UTC, elamaran11 commented on docs/addons/konveyor.md
> +
have screenshots of console.

2023-09-25 16:28 UTC, cbellone commented
hello @elamaran11

This is Celestino Bellone, I am an employee of Claranet Switzerland, and I am one of the maintainers of https://github.com/claranet-ch/konveyor-eks-blueprint-addon .

As requested, this is to confirm that Claranet will support the ongoing maintenance of the Konveyor EKS Addon.

Let me know if you need anything else from our side.

Thanks,
Celestino

2023-09-29 19:39 UTC, elamaran11 requested changes
@ariveroi Nice work. Update to `index.md` doc file is missing. Rest looks good atm.

2023-10-13 13:05 UTC, freschri submitted a review, later dismissed

2023-10-13 13:27 UTC, elamaran11 reviewed
@ariveroi Have a question

2023-10-23 12:45 UTC, elamaran11 approved these changes
LGTM.

2023-10-23 13:14 UTC, merged