added path support to code pipeline:
aws-quickstart/cdk-eks-blueprints pull request #844
Opened 2023-09-19 21:25 UTC by shapirov103

*Issue #, if available:* #633  (potentially)

*Description of changes:*
Added support for path specification with code pipeline.  See docs for usage.

Customers can define their blueprints IaC code under arbitrary path in the repo. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-19 21:28 UTC, elamaran11 requested changes
@shapirov103 Minor comment.

2023-09-19 21:28 UTC, elamaran11 commented on docs/pipelines.md
>  Note: the above code depends on the AWS secret `github-token` defined in the target account/region. The secret may be fined in one main region, and replicated to all target regions.
fined?

2023-10-02 18:12 UTC, shapirov103 commented on docs/pipelines.md
>  Note: the above code depends on the AWS secret `github-token` defined in the target account/region. The secret may be fined in one main region, and replicated to all target regions.
addressed, good catch!

2023-10-02 18:20 UTC, elamaran11 approved these changes
LGTM

2023-10-02 18:22 UTC, merged