Kuberay operator add-on
aws-quickstart/cdk-eks-blueprints pull request #849
Opened 2023-09-29 07:24 UTC by freschri

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-29 14:09 UTC, elamaran11 requested changes
@freschri Nice work but i have few questions:
1. Where is the ask from Partner side to build this addon though this will be an AWSome addition to Blueprints?
2. Are you planning to build a complete pattern to show usage of this KubeRay with a acomplete workload. We can also build a pattern with observability for this? If so please create a issue in patterns and observability repo
3. Update to doc index and mkdocs is missing too

2023-09-29 14:09 UTC, elamaran11 commented on docs/addons/kuberay-operator.md
> +# KubeRay Operator Add-on
Please make sure the doc index and mkdocs is updated

2023-09-29 14:09 UTC, elamaran11 commented on lib/addons/index.ts
>  export * from './kube-state-metrics';
this addon to be updated to example blueprint stack.

2023-09-29 15:12 UTC, freschri commented
> @freschri Nice work but i have few questions:
> 
>     1. Where is the ask from Partner side to build this addon though this will be an AWSome addition to Blueprints?
> 
>     2. Are you planning to build a complete pattern to show usage of this KubeRay with a acomplete workload. We can also build a pattern with observability for this? If so please create a issue in patterns and observability repo
> 
>     3. Update to doc index and mkdocs is missing too

the idea is to build the cdk equivalent of DoEKS's JARK stack, also presented here: https://aws.amazon.com/blogs/containers/deploy-generative-ai-models-on-amazon-eks/

2023-09-29 15:17 UTC, elamaran11 requested changes
@freschri Doc index is still not updated so this wont list in list of addons page. Also can you make sure you test the addon with blueprint-construction running it whole and let us know if it works. We can then run e2e

2023-09-30 15:49 UTC, elamaran11 approved these changes
LGTM. @shapirov103 Please check from your end.

2023-10-03 05:37 UTC, freschri commented on docs/addons/kuberay-operator.md
> +export class DatadogConstruct extends Construct {
sorry copy paste error. done.

2023-10-03 05:37 UTC, freschri commented on lib/addons/kuberay/index.ts
> +export interface KubeRayAddOnProps extends HelmAddOnUserProps {
there are no config values, please see here: https://ray-project.github.io/kuberay/deploy/helm/

2023-12-13 15:25 UTC, shapirov103 requested changes
@freschri please see my comment. we are targetting 1.13 release this week, there is a chance this addon can make it in.

2023-12-13 15:25 UTC, shapirov103 commented on lib/addons/kuberay/index.ts
> +  version: "1.0.0-rc.0",
Why use an RC version for the release? I see the have 1.0.0 - let's use that. We generally avoid using non-GA versions as default for the addon (with rare exceptions).

2023-12-13 15:26 UTC, shapirov103 commented
@freschri please igore the markdown broken links in the above check. We are addressing in a separate PR.

2023-12-15 20:37 UTC, elamaran11 commented
@freschri Are you planning to close this PR comments?

2024-02-05 02:26 UTC, shapirov103 commented
@freschri let's address minor feedback and please push something to retrigger the GH actions. I suppose the MD check that is failing should succeed now.

2024-02-05 08:20 UTC, freschri commented
> @freschri let's address minor feedback and please push something to retrigger the GH actions. I suppose the MD check that is failing should succeed now.

done

2024-02-12 04:22 UTC, shapirov103 commented
/do-e2e-tests

2024-02-13 22:12 UTC, shapirov103 commented
/do-e2e-tests

2024-02-13 23:12 UTC, shapirov103 commented
@freschri I am getting failure on stack destroy consistently, hence it cannot pass e2e. Have you tried dropping (deleting) the blueprint stack with this addon in place?

2024-02-15 16:00 UTC, shapirov103 commented
/do-e2e-tests

2024-02-15 16:05 UTC, shapirov103 commented
/do-e2e-tests

2024-02-15 17:24 UTC, shapirov103 commented
consistently leaves one ENI behind in a secondary subnet. this will have to be resolved before we include it in the release. @freschri

2024-02-28 08:12 UTC, freschri commented
> consistently leaves one ENI behind in a secondary subnet. this will have to be resolved before we include it in the release. @freschri

addressed

2024-02-28 08:13 UTC, freschri commented
/do-e2e-tests

2024-02-29 16:42 UTC, shapirov103 commented
/do-e2e-tests

2024-02-29 18:23 UTC, shapirov103 approved these changes
LGTM

2024-02-29 18:23 UTC, merged