Feature: AWS CloudWatch Container Insights Addon
aws-quickstart/cdk-eks-blueprints pull request #878
Opened 2023-11-15 00:16 UTC by 5herlocked

*Issue #, if available:* #872

*Description of changes:*
Added container insights add-on using CoreAddOn.
Added documentation for container insights along with what it's doing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-15 13:21 UTC, elamaran11 requested changes
@5herlocked Nice work on this new Addon. Some feedback.
1. Doc can be improved aligning to enhanced CW features of the addon
2. Managed Policy is missing
3. CW logs functionality is missing
4. mkdocs is missing
5. adding to doc index is missing
6. Are we not adding the blueprints stack. I would add and comment it.

2023-11-15 13:21 UTC, elamaran11 commented on lib/addons/cloud-watch-insights/index.ts
> +      const insightsAddon = new eks.CfnAddon(context.scope,  "CloudWatchInsightsAddon", {
You should be adding CloudWatch Managed Policy like [this](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/6ec2a2403ef34052c7d898f6d72a436b50fd589b/lib/addons/container-insights/index.ts#L35).

2023-11-15 13:21 UTC, elamaran11 commented on lib/addons/cloud-watch-insights/index.ts
> +   */
[Container Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Observability-EKS-addon.html#install-CloudWatch-Observability-EKS-addon-configuration:~:text=Optional)%20Additional%20configuration-,Container%20logs,-By%20default%2C%20the) option is missing. This means we can have a conflicts with CW Logs addon?

2023-11-15 13:21 UTC, elamaran11 commented on docs/addons/aws-container-insights.md
> +const addOn = new blueprints.addons.CloudWatchInsights();
Could we show additional different variants of usage like EBS, CW Logs etc?

2023-11-15 13:21 UTC, elamaran11 commented on lib/addons/cloud-watch-insights/index.ts
> +    @conflictsWith("AdotCollectorAddon", "CloudWatchAdotAddon")
`CloudWatchLogsAddon` is missing with `conflictsWith`

2023-11-15 13:21 UTC, elamaran11 commented on docs/addons/aws-container-insights.md
> +## View cluster level logs
Could we use doc and screenshots aligning to [the](https://aws.amazon.com/blogs/mt/new-container-insights-with-enhanced-observability-for-amazon-eks/) blog :
- Container Insights – Dashboard
- Top 10 list view
- Clusters overview
- Clusters performance monitoring
- CPU and memory utilization at the node level
- Containers performance monitoring
- Nodes performance monitoring
- Services performance monitoring
- Dashboard views for popular workloads
- New “ContainerInsights” metrics namespace
- Enhanced Container Insights – various metrics
- CW Logs
- EBS Performance
- Alarms?

2023-12-05 15:34 UTC, elamaran11 commented
@5herlocked Wanted to check if you need any help to make progress on this addon. We want to add this with next blueprints release.

2023-12-05 19:05 UTC, 5herlocked commented
I'll have this completed in a few weeks.

2023-12-11 21:12 UTC, elamaran11 commented
> I'll have this completed in a few weeks.

Could you plan to add this for upcoming blueprints release?

2023-12-12 19:55 UTC, 5herlocked commented
Resolved most of the requested changes, still working on the documentation.

2023-12-12 20:51 UTC, elamaran11 approved these changes
LGTM. @shapirov103 Please check from your end.

2023-12-12 21:20 UTC, shapirov103 reviewed
@5herlocked 

Looks great, however the way it stands now it will be very confusing for the customers to select the right addon, especially choosing between ContainerInsightsAddon and this addon. 

So let's apply the following changes:

1. deprecate the current container insights addon (e..g similar to what we did for calico)
2. update documentation for the deprecated addon and specify that there will be no maintenace on it and customers should move over to the CloudWatchInsightsAddon. 
3. In the docs for this addon, also call out that it is replacing the current CI addon.

2023-12-13 15:08 UTC, shapirov103 requested changes
Please see the recommended naming and deprecation changes, otherwise looks great.

2023-12-14 02:10 UTC, elamaran11 reviewed
Nice work, Please make sure the screenshots are up-to-date after your testing.

2023-12-14 16:44 UTC, elamaran11 commented
@shapirov103 I was able to pull the fork and test, everything works fine. I can see CI in CW Console. Please proceed with e2e and merge.

2023-12-14 16:46 UTC, merged