[Feature] Service-specific ACKAddOns
aws-quickstart/cdk-eks-blueprints pull request #978
Opened 2024-04-05 19:21 UTC by dwright20

*Issue #, if available:* [974](https://github.com/aws-quickstart/cdk-eks-blueprints/issues/974)

*Description of changes:*
- Added service-specific ACKAddOn classes that are individually annotated with `@supportsALL` or `supportsX86` per [ACK Registry](https://gallery.ecr.aws/aws-controllers-k8s)
- Added unit tests for each created addon that tests attempting to create the addon using an x86 builder (`EksBlueprint.builder()`) & an ARM builder (`GravitonBuilder()`)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-05 20:35 UTC, elamaran11 requested changes
@dwright20 First of all thankyou so much for you PR. Especially liked the test scripts a lot. Fundmentally, I dont think we should use this design approach of one class per ACK chart, this will make the design difficult the expand for future addons. I think we should stick to existing design with following as design choices:
1. Add `supportsALL` to original ACK addon and create another enum of list of services which do not support ARM, In the `ACKAddon` if the AWS Service is in the ENUM list of non-ARM supported like memoryDB and if Nodes are ARM, we should error out. 
2. Add `supportsALL` to original ACK addon along with adding a documentation to say ARM is not supported today for MemoryDB (This is more of temp solution).
@shapirov103 Any other design choices?

2024-04-05 20:35 UTC, elamaran11 commented on lib/addons/ack/service.ts
> +export class ACMAckAddOn extends AckAddOn {
I dont think we should use this design approach of one class extension per ACK chart, this will make the design difficult the expand.

2024-05-01 04:12 UTC, shapirov103 reviewed
@dwright20 seems like a bit of duplication going on, but on the other hand it creates a placeholder for each ACK. 

Ideally, we would like to keep the approach generic so that little maintenance is needed.

I don't want to dismiss the design choice, however, let's use the principle of "as simple as possible but not simpler".

Let's say we change the existing approach slightly and add the target CPU architecture to the `serviceMappings.ts`, then implement this support in the `AckAddOn`. We will also add supportsAll to the AckAddOn by default and add code that will handle exclusions.  This can be done by replicating some of the code that we have in the supportsX86 and such decorators. 

If the above is implemented, what else is missing that requires explicit class per Ack controller implementation? Do you envision additional use cases?

2024-06-19 04:31 UTC, shapirov103 commented
@dwright20 please see my comment and let me know what you think. I mentioned an approach to simplify the design approach to make it easier for us to maintain. This has been open for a while.

2024-11-17 00:05 UTC, closed without merging